import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'fr' | 'es' | 'de' | 'it' | 'zh' | 'ja' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.portfolio': 'Portfolio',
    'nav.philosophy': 'Philosophy',
    'nav.legacy': 'Legacy',
    'nav.intelligence': 'Intelligence',
    'nav.concierge': 'Concierge',
    
    // Hero
    'hero.exclusively': 'Exclusively Urban Nest',
    'hero.title1': 'The Art of',
    'hero.title2': 'Quiet Luxury.',
    'hero.description': 'A curated collection of residences where architectural soul meets precision engineering.',
    'hero.discover': 'Discover Estates',
    'hero.viewings': 'Private Viewings',
    
    // App sections
    'app.excellence': 'Excellence',
    'app.living': 'Living is an',
    'app.acquired': 'acquired taste.',
    'app.belief': 'At Urban Nest, we believe a home is the most profound expression of one\'s identity. We represent the avant-garde of global real estate.',
    'app.inquire': 'Inquire Privately',
    'app.future': 'The future',
    'app.residential': 'is residential.',
    'app.request': 'Request Presentation',
    'app.contact': 'Contact Advisory',
    
    // ScrollReveal
    'scroll.evolution': 'Evolution',
    'scroll.beyond': 'Beyond Walls.',
    'scroll.engineering': 'Our engineering team spends over 4,000 hours on every project ensuring that every joint, material, and light fixture is a masterpiece of intent.',
    
    // PropertyGrid
    'property.collections': 'The Collections',
    'property.excellence': 'Curated Excellence.',
    'property.all': 'All Listings',
    'property.exclusive': 'Exclusive',
    'property.archived': 'Archived',
    'property.explore': 'Explore Space',
    'property.bedrooms': 'Bedrooms',
    
    // Footer
    'footer.explore': 'Explore',
    'footer.residential': 'Residential',
    'footer.commercial': 'Commercial',
    'footer.architecture': 'Architecture',
    'footer.designLab': 'Design Lab',
    'footer.services': 'Services',
    'footer.advisory': 'Private Advisory',
    'footer.relocation': 'Relocation',
    'footer.staging': 'Staging',
    'footer.financing': 'Financing',
    'footer.company': 'Company',
    'footer.story': 'Our Story',
    'footer.impact': 'Impact',
    'footer.press': 'Press',
    'footer.careers': 'Careers',
    'footer.offices': 'Urban Nest Offices',
    'footer.copyright': '© 2024 Urban Nest Estates. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Settings',
    
    // Concierge Form
    'form.title': 'Concierge Inquiry',
    'form.subtitle': 'We\'ll respond within 24 hours',
    'form.name': 'Full Name',
    'form.email': 'Email Address',
    'form.phone': 'Phone Number',
    'form.inquiry': 'Type of Inquiry',
    'form.property': 'Property of Interest',
    'form.timeline': 'Timeline',
    'form.budget': 'Budget Range',
    'form.message': 'Additional Message',
    'form.select': 'Select an option',
    'form.viewing': 'Private Viewing',
    'form.information': 'Property Information',
    'form.investment': 'Investment Inquiry',
    'form.consultation': 'Design Consultation',
    'form.other': 'Other',
    'form.selectTimeline': 'Select timeline',
    'form.immediate': 'Immediate',
    'form.months1-3': '1-3 Months',
    'form.months3-6': '3-6 Months',
    'form.months6-12': '6-12 Months',
    'form.exploring': 'Just Exploring',
    'form.selectRange': 'Select range',
    'form.under1m': 'Under ₹5 Cr',
    'form.range1-3m': '₹5 Cr - ₹15 Cr',
    'form.range3-5m': '₹15 Cr - ₹25 Cr',
    'form.range5-10m': '₹25 Cr - ₹50 Cr',
    'form.range10mPlus': '₹50 Cr+',
    'form.confidential': 'Confidential',
    'form.placeholder.name': 'Rajesh Kumar',
    'form.placeholder.email': 'rajesh@example.com',
    'form.placeholder.phone': '+91 98765 43210',
    'form.placeholder.property': 'Property name or location',
    'form.placeholder.message': 'Tell us more about your requirements...',
    'form.cancel': 'Cancel',
    'form.submit': 'Submit Inquiry',
    'form.submitting': 'Submitting...',
    'form.thankYou': 'Thank You',
    'form.success': 'Your inquiry has been received. Our concierge team will contact you shortly.',
    'form.error': 'There was an error submitting your form. Please try again.',
    
    // AI Chat
    'chat.title': 'Urban Nest Concierge',
    'chat.available': 'Available Now',
    'chat.placeholder': 'Inquire about architecture or availability...',
    'chat.greeting': 'Good day. I am your Urban Nest Concierge. How may I assist you with our portfolio today?',
  },
  fr: {
    // Navbar
    'nav.portfolio': 'Portfolio',
    'nav.philosophy': 'Philosophie',
    'nav.legacy': 'Héritage',
    'nav.intelligence': 'Intelligence',
    'nav.concierge': 'Conciergerie',
    
    // Hero
    'hero.exclusively': 'Exclusivement Urban Nest',
    'hero.title1': 'L\'Art du',
    'hero.title2': 'Luxe Discret.',
    'hero.description': 'Une collection soigneusement sélectionnée de résidences où l\'âme architecturale rencontre l\'ingénierie de précision.',
    'hero.discover': 'Découvrir les Domaines',
    'hero.viewings': 'Visites Privées',
    
    // App sections
    'app.excellence': 'Excellence',
    'app.living': 'Vivre est un',
    'app.acquired': 'goût acquis.',
    'app.belief': 'Chez Urban Nest, nous croyons qu\'une maison est l\'expression la plus profonde de l\'identité. Nous représentons l\'avant-garde de l\'immobilier mondial.',
    'app.inquire': 'Renseignements Privés',
    'app.future': 'L\'avenir',
    'app.residential': 'est résidentiel.',
    'app.request': 'Demander une Présentation',
    'app.contact': 'Contacter un Conseiller',
    
    // ScrollReveal
    'scroll.evolution': 'Évolution',
    'scroll.beyond': 'Au-delà des Murs.',
    'scroll.engineering': 'Notre équipe d\'ingénierie consacre plus de 4 000 heures à chaque projet, garantissant que chaque joint, matériau et luminaire est un chef-d\'œuvre d\'intention.',
    
    // PropertyGrid
    'property.collections': 'Les Collections',
    'property.excellence': 'Excellence Sélectionnée.',
    'property.all': 'Toutes les Annonces',
    'property.exclusive': 'Exclusif',
    'property.archived': 'Archivé',
    'property.explore': 'Explorer l\'Espace',
    'property.bedrooms': 'Chambres',
    
    // Footer
    'footer.explore': 'Explorer',
    'footer.residential': 'Résidentiel',
    'footer.commercial': 'Commercial',
    'footer.architecture': 'Architecture',
    'footer.designLab': 'Laboratoire de Design',
    'footer.services': 'Services',
    'footer.advisory': 'Conseil Privé',
    'footer.relocation': 'Relocalisation',
    'footer.staging': 'Mise en Scène',
    'footer.financing': 'Financement',
    'footer.company': 'Entreprise',
    'footer.story': 'Notre Histoire',
    'footer.impact': 'Impact',
    'footer.press': 'Presse',
    'footer.careers': 'Carrières',
    'footer.offices': 'Bureaux Urban Nest',
    'footer.copyright': '© 2024 Urban Nest Estates. Tous droits réservés.',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': 'Conditions d\'Utilisation',
    'footer.cookies': 'Paramètres des Cookies',
    
    // Concierge Form
    'form.title': 'Demande de Conciergerie',
    'form.subtitle': 'Nous répondrons dans les 24 heures',
    'form.name': 'Nom Complet',
    'form.email': 'Adresse Email',
    'form.phone': 'Numéro de Téléphone',
    'form.inquiry': 'Type de Demande',
    'form.property': 'Propriété d\'Intérêt',
    'form.timeline': 'Délai',
    'form.budget': 'Gamme de Budget',
    'form.message': 'Message Supplémentaire',
    'form.select': 'Sélectionner une option',
    'form.viewing': 'Visite Privée',
    'form.information': 'Informations sur la Propriété',
    'form.investment': 'Demande d\'Investissement',
    'form.consultation': 'Consultation en Design',
    'form.other': 'Autre',
    'form.selectTimeline': 'Sélectionner le délai',
    'form.immediate': 'Immédiat',
    'form.months1-3': '1-3 Mois',
    'form.months3-6': '3-6 Mois',
    'form.months6-12': '6-12 Mois',
    'form.exploring': 'Juste Explorer',
    'form.selectRange': 'Sélectionner la gamme',
    'form.under1m': 'Moins de ₹5 Cr',
    'form.range1-3m': '₹5 Cr - ₹15 Cr',
    'form.range3-5m': '₹15 Cr - ₹25 Cr',
    'form.range5-10m': '₹25 Cr - ₹50 Cr',
    'form.range10mPlus': '₹50 Cr+',
    'form.confidential': 'Confidentiel',
    'form.placeholder.name': 'Jean Dupont',
    'form.placeholder.email': 'jean@exemple.com',
    'form.placeholder.phone': '+91 98765 43210',
    'form.placeholder.property': 'Nom ou emplacement de la propriété',
    'form.placeholder.message': 'Dites-nous en plus sur vos exigences...',
    'form.cancel': 'Annuler',
    'form.submit': 'Soumettre la Demande',
    'form.submitting': 'Envoi en cours...',
    'form.thankYou': 'Merci',
    'form.success': 'Votre demande a été reçue. Notre équipe de conciergerie vous contactera sous peu.',
    'form.error': 'Une erreur s\'est produite lors de l\'envoi de votre formulaire. Veuillez réessayer.',
    
    // AI Chat
    'chat.title': 'Conciergerie Urban Nest',
    'chat.available': 'Disponible Maintenant',
    'chat.placeholder': 'Renseignez-vous sur l\'architecture ou la disponibilité...',
    'chat.greeting': 'Bonjour. Je suis votre Concierge Urban Nest. Comment puis-je vous aider avec notre portfolio aujourd\'hui?',
  },
  es: {
    // Navbar
    'nav.portfolio': 'Portafolio',
    'nav.philosophy': 'Filosofía',
    'nav.legacy': 'Legado',
    'nav.intelligence': 'Inteligencia',
    'nav.concierge': 'Conserjería',
    
    // Hero
    'hero.exclusively': 'Exclusivamente Urban Nest',
    'hero.title1': 'El Arte del',
    'hero.title2': 'Lujo Discreto.',
    'hero.description': 'Una colección curada de residencias donde el alma arquitectónica se encuentra con la ingeniería de precisión.',
    'hero.discover': 'Descubrir Propiedades',
    'hero.viewings': 'Visitas Privadas',
    
    // App sections
    'app.excellence': 'Excelencia',
    'app.living': 'Vivir es un',
    'app.acquired': 'gusto adquirido.',
    'app.belief': 'En Urban Nest, creemos que un hogar es la expresión más profunda de la identidad. Representamos la vanguardia del mercado inmobiliario global.',
    'app.inquire': 'Consultar en Privado',
    'app.future': 'El futuro',
    'app.residential': 'es residencial.',
    'app.request': 'Solicitar Presentación',
    'app.contact': 'Contactar Asesor',
    
    // ScrollReveal
    'scroll.evolution': 'Evolución',
    'scroll.beyond': 'Más Allá de las Paredes.',
    'scroll.engineering': 'Nuestro equipo de ingeniería dedica más de 4,000 horas a cada proyecto, asegurando que cada junta, material y luminaria sea una obra maestra de intención.',
    
    // PropertyGrid
    'property.collections': 'Las Colecciones',
    'property.excellence': 'Excelencia Curada.',
    'property.all': 'Todos los Listados',
    'property.exclusive': 'Exclusivo',
    'property.archived': 'Archivado',
    'property.explore': 'Explorar Espacio',
    'property.bedrooms': 'Habitaciones',
    
    // Footer
    'footer.explore': 'Explorar',
    'footer.residential': 'Residencial',
    'footer.commercial': 'Comercial',
    'footer.architecture': 'Arquitectura',
    'footer.designLab': 'Laboratorio de Diseño',
    'footer.services': 'Servicios',
    'footer.advisory': 'Asesoría Privada',
    'footer.relocation': 'Reubicación',
    'footer.staging': 'Puesta en Escena',
    'footer.financing': 'Financiamiento',
    'footer.company': 'Empresa',
    'footer.story': 'Nuestra Historia',
    'footer.impact': 'Impacto',
    'footer.press': 'Prensa',
    'footer.careers': 'Carreras',
    'footer.offices': 'Oficinas Urban Nest',
    'footer.copyright': '© 2024 Urban Nest Estates. Todos los derechos reservados.',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.cookies': 'Configuración de Cookies',
    
    // Concierge Form
    'form.title': 'Consulta de Conserjería',
    'form.subtitle': 'Responderemos en 24 horas',
    'form.name': 'Nombre Completo',
    'form.email': 'Dirección de Email',
    'form.phone': 'Número de Teléfono',
    'form.inquiry': 'Tipo de Consulta',
    'form.property': 'Propiedad de Interés',
    'form.timeline': 'Plazo',
    'form.budget': 'Rango de Presupuesto',
    'form.message': 'Mensaje Adicional',
    'form.select': 'Seleccionar una opción',
    'form.viewing': 'Visita Privada',
    'form.information': 'Información de Propiedad',
    'form.investment': 'Consulta de Inversión',
    'form.consultation': 'Consulta de Diseño',
    'form.other': 'Otro',
    'form.selectTimeline': 'Seleccionar plazo',
    'form.immediate': 'Inmediato',
    'form.months1-3': '1-3 Meses',
    'form.months3-6': '3-6 Meses',
    'form.months6-12': '6-12 Meses',
    'form.exploring': 'Solo Explorando',
    'form.selectRange': 'Seleccionar rango',
    'form.under1m': 'Menos de ₹5 Cr',
    'form.range1-3m': '₹5 Cr - ₹15 Cr',
    'form.range3-5m': '₹15 Cr - ₹25 Cr',
    'form.range5-10m': '₹25 Cr - ₹50 Cr',
    'form.range10mPlus': '₹50 Cr+',
    'form.confidential': 'Confidencial',
    'form.placeholder.name': 'Juan Pérez',
    'form.placeholder.email': 'juan@ejemplo.com',
    'form.placeholder.phone': '+91 98765 43210',
    'form.placeholder.property': 'Nombre o ubicación de la propiedad',
    'form.placeholder.message': 'Cuéntanos más sobre tus requisitos...',
    'form.cancel': 'Cancelar',
    'form.submit': 'Enviar Consulta',
    'form.submitting': 'Enviando...',
    'form.thankYou': 'Gracias',
    'form.success': 'Su consulta ha sido recibida. Nuestro equipo de conserjería se pondrá en contacto con usted pronto.',
    'form.error': 'Hubo un error al enviar su formulario. Por favor, inténtelo de nuevo.',
    
    // AI Chat
    'chat.title': 'Conserjería Urban Nest',
    'chat.available': 'Disponible Ahora',
    'chat.placeholder': 'Consulte sobre arquitectura o disponibilidad...',
    'chat.greeting': 'Buen día. Soy su Conserje Urban Nest. ¿Cómo puedo ayudarle con nuestro portafolio hoy?',
  },
  de: {
    // Navbar
    'nav.portfolio': 'Portfolio',
    'nav.philosophy': 'Philosophie',
    'nav.legacy': 'Vermächtnis',
    'nav.intelligence': 'Intelligenz',
    'nav.concierge': 'Concierge',
    
    // Hero
    'hero.exclusively': 'Exklusiv Urban Nest',
    'hero.title1': 'Die Kunst des',
    'hero.title2': 'Stillen Luxus.',
    'hero.description': 'Eine kuratierte Sammlung von Residenzen, in der architektonische Seele auf Präzisionsingenieurwesen trifft.',
    'hero.discover': 'Anwesen Entdecken',
    'hero.viewings': 'Private Besichtigungen',
    
    // App sections
    'app.excellence': 'Exzellenz',
    'app.living': 'Leben ist ein',
    'app.acquired': 'erworbener Geschmack.',
    'app.belief': 'Bei Urban Nest glauben wir, dass ein Zuhause der tiefste Ausdruck der Identität ist. Wir vertreten die Avantgarde des globalen Immobilienmarkts.',
    'app.inquire': 'Privat Anfragen',
    'app.future': 'Die Zukunft',
    'app.residential': 'ist wohnlich.',
    'app.request': 'Präsentation Anfordern',
    'app.contact': 'Berater Kontaktieren',
    
    // ScrollReveal
    'scroll.evolution': 'Evolution',
    'scroll.beyond': 'Jenseits der Wände.',
    'scroll.engineering': 'Unser Ingenieurteam verbringt über 4.000 Stunden an jedem Projekt und stellt sicher, dass jede Verbindung, jedes Material und jede Leuchte ein Meisterwerk der Absicht ist.',
    
    // PropertyGrid
    'property.collections': 'Die Kollektionen',
    'property.excellence': 'Kuratierte Exzellenz.',
    'property.all': 'Alle Angebote',
    'property.exclusive': 'Exklusiv',
    'property.archived': 'Archiviert',
    'property.explore': 'Raum Erkunden',
    'property.bedrooms': 'Schlafzimmer',
    
    // Footer
    'footer.explore': 'Erkunden',
    'footer.residential': 'Wohnimmobilien',
    'footer.commercial': 'Gewerbeimmobilien',
    'footer.architecture': 'Architektur',
    'footer.designLab': 'Designlabor',
    'footer.services': 'Dienstleistungen',
    'footer.advisory': 'Private Beratung',
    'footer.relocation': 'Umzug',
    'footer.staging': 'Staging',
    'footer.financing': 'Finanzierung',
    'footer.company': 'Unternehmen',
    'footer.story': 'Unsere Geschichte',
    'footer.impact': 'Wirkung',
    'footer.press': 'Presse',
    'footer.careers': 'Karrieren',
    'footer.offices': 'Urban Nest Büros',
    'footer.copyright': '© 2024 Urban Nest Estates. Alle Rechte vorbehalten.',
    'footer.privacy': 'Datenschutzrichtlinie',
    'footer.terms': 'Nutzungsbedingungen',
    'footer.cookies': 'Cookie-Einstellungen',
    
    // Concierge Form
    'form.title': 'Concierge-Anfrage',
    'form.subtitle': 'Wir antworten innerhalb von 24 Stunden',
    'form.name': 'Vollständiger Name',
    'form.email': 'E-Mail-Adresse',
    'form.phone': 'Telefonnummer',
    'form.inquiry': 'Art der Anfrage',
    'form.property': 'Interessante Immobilie',
    'form.timeline': 'Zeitrahmen',
    'form.budget': 'Budgetbereich',
    'form.message': 'Zusätzliche Nachricht',
    'form.select': 'Option auswählen',
    'form.viewing': 'Private Besichtigung',
    'form.information': 'Immobilieninformationen',
    'form.investment': 'Investitionsanfrage',
    'form.consultation': 'Designberatung',
    'form.other': 'Andere',
    'form.selectTimeline': 'Zeitrahmen auswählen',
    'form.immediate': 'Sofort',
    'form.months1-3': '1-3 Monate',
    'form.months3-6': '3-6 Monate',
    'form.months6-12': '6-12 Monate',
    'form.exploring': 'Nur Erkunden',
    'form.selectRange': 'Bereich auswählen',
    'form.under1m': 'Unter ₹5 Cr',
    'form.range1-3m': '₹5 Cr - ₹15 Cr',
    'form.range3-5m': '₹15 Cr - ₹25 Cr',
    'form.range5-10m': '₹25 Cr - ₹50 Cr',
    'form.range10mPlus': '₹50 Cr+',
    'form.confidential': 'Vertraulich',
    'form.placeholder.name': 'Max Mustermann',
    'form.placeholder.email': 'max@beispiel.de',
    'form.placeholder.phone': '+91 98765 43210',
    'form.placeholder.property': 'Immobilienname oder Standort',
    'form.placeholder.message': 'Erzählen Sie uns mehr über Ihre Anforderungen...',
    'form.cancel': 'Abbrechen',
    'form.submit': 'Anfrage Absenden',
    'form.submitting': 'Wird gesendet...',
    'form.thankYou': 'Vielen Dank',
    'form.success': 'Ihre Anfrage wurde erhalten. Unser Concierge-Team wird Sie in Kürze kontaktieren.',
    'form.error': 'Beim Senden Ihres Formulars ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.',
    
    // AI Chat
    'chat.title': 'Urban Nest Concierge',
    'chat.available': 'Jetzt Verfügbar',
    'chat.placeholder': 'Fragen Sie nach Architektur oder Verfügbarkeit...',
    'chat.greeting': 'Guten Tag. Ich bin Ihr Urban Nest Concierge. Wie kann ich Ihnen heute mit unserem Portfolio helfen?',
  },
  it: {
    // Navbar
    'nav.portfolio': 'Portfolio',
    'nav.philosophy': 'Filosofia',
    'nav.legacy': 'Eredità',
    'nav.intelligence': 'Intelligenza',
    'nav.concierge': 'Concierge',
    
    // Hero
    'hero.exclusively': 'Esclusivamente Urban Nest',
    'hero.title1': 'L\'Arte del',
    'hero.title2': 'Lusso Discreto.',
    'hero.description': 'Una collezione curata di residenze dove l\'anima architettonica incontra l\'ingegneria di precisione.',
    'hero.discover': 'Scopri Tenute',
    'hero.viewings': 'Visite Private',
    
    // App sections
    'app.excellence': 'Eccellenza',
    'app.living': 'Vivere è un',
    'app.acquired': 'gusto acquisito.',
    'app.belief': 'In Urban Nest, crediamo che una casa sia l\'espressione più profonda dell\'identità. Rappresentiamo l\'avanguardia del mercato immobiliare globale.',
    'app.inquire': 'Richiedi in Privato',
    'app.future': 'Il futuro',
    'app.residential': 'è residenziale.',
    'app.request': 'Richiedi Presentazione',
    'app.contact': 'Contatta Consulente',
    
    // ScrollReveal
    'scroll.evolution': 'Evoluzione',
    'scroll.beyond': 'Oltre le Mura.',
    'scroll.detail': 'Dettaglio Inflessibile.',
    'scroll.engineering': 'Il nostro team di ingegneria dedica oltre 4.000 ore a ogni progetto, assicurando che ogni giunto, materiale e apparecchio di illuminazione sia un capolavoro di intento.',
    
    // PropertyGrid
    'property.collections': 'Le Collezioni',
    'property.excellence': 'Eccellenza Curata.',
    'property.all': 'Tutti gli Annunci',
    'property.exclusive': 'Esclusivo',
    'property.archived': 'Archiviato',
    'property.explore': 'Esplora Spazio',
    'property.bedrooms': 'Camere da Letto',
    
    // Footer
    'footer.explore': 'Esplora',
    'footer.residential': 'Residenziale',
    'footer.commercial': 'Commerciale',
    'footer.architecture': 'Architettura',
    'footer.designLab': 'Laboratorio di Design',
    'footer.services': 'Servizi',
    'footer.advisory': 'Consulenza Privata',
    'footer.relocation': 'Trasferimento',
    'footer.staging': 'Allestimento',
    'footer.financing': 'Finanziamento',
    'footer.company': 'Azienda',
    'footer.story': 'La Nostra Storia',
    'footer.impact': 'Impatto',
    'footer.press': 'Stampa',
    'footer.careers': 'Carriere',
    'footer.offices': 'Uffici Urban Nest',
    'footer.copyright': '© 2024 Urban Nest Estates. Tutti i diritti riservati.',
    'footer.privacy': 'Politica sulla Privacy',
    'footer.terms': 'Termini di Servizio',
    'footer.cookies': 'Impostazioni Cookie',
    
    // Concierge Form
    'form.title': 'Richiesta Concierge',
    'form.subtitle': 'Risponderemo entro 24 ore',
    'form.name': 'Nome Completo',
    'form.email': 'Indirizzo Email',
    'form.phone': 'Numero di Telefono',
    'form.inquiry': 'Tipo di Richiesta',
    'form.property': 'Proprietà di Interesse',
    'form.timeline': 'Tempi',
    'form.budget': 'Fascia di Budget',
    'form.message': 'Messaggio Aggiuntivo',
    'form.select': 'Seleziona un\'opzione',
    'form.viewing': 'Visita Privata',
    'form.information': 'Informazioni Proprietà',
    'form.investment': 'Richiesta Investimento',
    'form.consultation': 'Consulenza Design',
    'form.other': 'Altro',
    'form.selectTimeline': 'Seleziona tempi',
    'form.immediate': 'Immediato',
    'form.months1-3': '1-3 Mesi',
    'form.months3-6': '3-6 Mesi',
    'form.months6-12': '6-12 Mesi',
    'form.exploring': 'Solo Esplorando',
    'form.selectRange': 'Seleziona fascia',
    'form.under1m': 'Sotto ₹5 Cr',
    'form.range1-3m': '₹5 Cr - ₹15 Cr',
    'form.range3-5m': '₹15 Cr - ₹25 Cr',
    'form.range5-10m': '₹25 Cr - ₹50 Cr',
    'form.range10mPlus': '₹50 Cr+',
    'form.confidential': 'Riservato',
    'form.placeholder.name': 'Mario Rossi',
    'form.placeholder.email': 'mario@esempio.it',
    'form.placeholder.phone': '+91 98765 43210',
    'form.placeholder.property': 'Nome o posizione della proprietà',
    'form.placeholder.message': 'Raccontaci di più sui tuoi requisiti...',
    'form.cancel': 'Annulla',
    'form.submit': 'Invia Richiesta',
    'form.submitting': 'Invio in corso...',
    'form.thankYou': 'Grazie',
    'form.success': 'La tua richiesta è stata ricevuta. Il nostro team concierge ti contatterà a breve.',
    'form.error': 'Si è verificato un errore durante l\'invio del modulo. Riprova.',
    
    // AI Chat
    'chat.title': 'Concierge Urban Nest',
    'chat.available': 'Disponibile Ora',
    'chat.placeholder': 'Chiedi informazioni su architettura o disponibilità...',
    'chat.greeting': 'Buongiorno. Sono il tuo Concierge Urban Nest. Come posso aiutarti con il nostro portfolio oggi?',
  },
  zh: {
    // Navbar
    'nav.portfolio': '作品集',
    'nav.philosophy': '理念',
    'nav.legacy': '传承',
    'nav.intelligence': '智能',
    'nav.concierge': '礼宾服务',
    
    // Hero
    'hero.exclusively': '独家 Urban Nest',
    'hero.title1': '静谧',
    'hero.title2': '奢华的艺术。',
    'hero.description': '精心策划的住宅系列，建筑灵魂与精密工程完美融合。',
    'hero.discover': '探索庄园',
    'hero.viewings': '私人参观',
    
    // App sections
    'app.excellence': '卓越',
    'app.living': '生活是一种',
    'app.acquired': '后天培养的品味。',
    'app.belief': '在 Urban Nest，我们相信家是一个人身份最深刻的表达。我们代表全球房地产的前沿。',
    'app.inquire': '私人咨询',
    'app.future': '未来',
    'app.residential': '是住宅。',
    'app.request': '请求演示',
    'app.contact': '联系顾问',
    
    // ScrollReveal
    'scroll.evolution': '进化',
    'scroll.beyond': '超越墙壁。',
    'scroll.detail': '毫不妥协的细节。',
    'scroll.engineering': '我们的工程团队在每个项目上花费超过 4,000 小时，确保每个接缝、材料和灯具都是意图的杰作。',
    
    // PropertyGrid
    'property.collections': '系列',
    'property.excellence': '精选卓越。',
    'property.all': '所有房源',
    'property.exclusive': '独家',
    'property.archived': '已归档',
    'property.explore': '探索空间',
    'property.bedrooms': '卧室',
    
    // Footer
    'footer.explore': '探索',
    'footer.residential': '住宅',
    'footer.commercial': '商业',
    'footer.architecture': '建筑',
    'footer.designLab': '设计实验室',
    'footer.services': '服务',
    'footer.advisory': '私人咨询',
    'footer.relocation': '搬迁',
    'footer.staging': '布置',
    'footer.financing': '融资',
    'footer.company': '公司',
    'footer.story': '我们的故事',
    'footer.impact': '影响',
    'footer.press': '新闻',
    'footer.careers': '职业',
    'footer.offices': 'Urban Nest 办公室',
    'footer.copyright': '© 2024 Urban Nest Estates. 保留所有权利。',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.cookies': 'Cookie 设置',
    
    // Concierge Form
    'form.title': '礼宾咨询',
    'form.subtitle': '我们将在 24 小时内回复',
    'form.name': '全名',
    'form.email': '电子邮件地址',
    'form.phone': '电话号码',
    'form.inquiry': '咨询类型',
    'form.property': '感兴趣的房产',
    'form.timeline': '时间表',
    'form.budget': '预算范围',
    'form.message': '附加信息',
    'form.select': '选择选项',
    'form.viewing': '私人参观',
    'form.information': '房产信息',
    'form.investment': '投资咨询',
    'form.consultation': '设计咨询',
    'form.other': '其他',
    'form.selectTimeline': '选择时间表',
    'form.immediate': '立即',
    'form.months1-3': '1-3 个月',
    'form.months3-6': '3-6 个月',
    'form.months6-12': '6-12 个月',
    'form.exploring': '仅浏览',
    'form.selectRange': '选择范围',
    'form.under1m': '低于 ₹5 千万',
    'form.range1-3m': '₹5 千万 - ₹1.5 亿',
    'form.range3-5m': '₹1.5 亿 - ₹2.5 亿',
    'form.range5-10m': '₹2.5 亿 - ₹5 亿',
    'form.range10mPlus': '₹5 亿以上',
    'form.confidential': '保密',
    'form.placeholder.name': '张三',
    'form.placeholder.email': 'zhang@example.com',
    'form.placeholder.phone': '+91 98765 43210',
    'form.placeholder.property': '房产名称或位置',
    'form.placeholder.message': '告诉我们更多关于您的需求...',
    'form.cancel': '取消',
    'form.submit': '提交咨询',
    'form.submitting': '提交中...',
    'form.thankYou': '谢谢',
    'form.success': '您的咨询已收到。我们的礼宾团队将很快与您联系。',
    'form.error': '提交表单时出错。请重试。',
    
    // AI Chat
    'chat.title': 'Urban Nest 礼宾',
    'chat.available': '现在可用',
    'chat.placeholder': '咨询建筑或可用性...',
    'chat.greeting': '您好。我是您的 Urban Nest 礼宾。今天我可以如何帮助您了解我们的作品集？',
  },
  ja: {
    // Navbar
    'nav.portfolio': 'ポートフォリオ',
    'nav.philosophy': '哲学',
    'nav.legacy': 'レガシー',
    'nav.intelligence': 'インテリジェンス',
    'nav.concierge': 'コンシェルジュ',
    
    // Hero
    'hero.exclusively': '独占 Urban Nest',
    'hero.title1': '静かな',
    'hero.title2': '贅沢の芸術。',
    'hero.description': '建築の魂が精密工学と出会う、厳選された住宅コレクション。',
    'hero.discover': 'エステートを発見',
    'hero.viewings': 'プライベート見学',
    
    // App sections
    'app.excellence': '卓越',
    'app.living': '生きることは',
    'app.acquired': '後天的な味覚です。',
    'app.belief': 'Urban Nestでは、家はアイデンティティの最も深い表現であると信じています。私たちはグローバル不動産の前衛を代表しています。',
    'app.inquire': '非公開でお問い合わせ',
    'app.future': '未来は',
    'app.residential': '住宅です。',
    'app.request': 'プレゼンテーションをリクエスト',
    'app.contact': 'アドバイザーに連絡',
    
    // ScrollReveal
    'scroll.evolution': '進化',
    'scroll.beyond': '壁を超えて。',
    'scroll.detail': '妥協のない詳細。',
    'scroll.engineering': '私たちのエンジニアリングチームは、各プロジェクトに4,000時間以上を費やし、すべての接合部、材料、照明器具が意図の傑作であることを保証しています。',
    
    // PropertyGrid
    'property.collections': 'コレクション',
    'property.excellence': '厳選された卓越性。',
    'property.all': 'すべてのリスト',
    'property.exclusive': '独占',
    'property.archived': 'アーカイブ済み',
    'property.explore': 'スペースを探索',
    'property.bedrooms': '寝室',
    
    // Footer
    'footer.explore': '探索',
    'footer.residential': '住宅',
    'footer.commercial': '商業',
    'footer.architecture': '建築',
    'footer.designLab': 'デザインラボ',
    'footer.services': 'サービス',
    'footer.advisory': 'プライベートアドバイザリー',
    'footer.relocation': '移転',
    'footer.staging': 'ステージング',
    'footer.financing': 'ファイナンス',
    'footer.company': '会社',
    'footer.story': '私たちの物語',
    'footer.impact': '影響',
    'footer.press': 'プレス',
    'footer.careers': 'キャリア',
    'footer.offices': 'Urban Nestオフィス',
    'footer.copyright': '© 2024 Urban Nest Estates. 全著作権所有。',
    'footer.privacy': 'プライバシーポリシー',
    'footer.terms': '利用規約',
    'footer.cookies': 'Cookie設定',
    
    // Concierge Form
    'form.title': 'コンシェルジュお問い合わせ',
    'form.subtitle': '24時間以内に返信いたします',
    'form.name': 'フルネーム',
    'form.email': 'メールアドレス',
    'form.phone': '電話番号',
    'form.inquiry': 'お問い合わせの種類',
    'form.property': '興味のある物件',
    'form.timeline': 'タイムライン',
    'form.budget': '予算範囲',
    'form.message': '追加メッセージ',
    'form.select': 'オプションを選択',
    'form.viewing': 'プライベート見学',
    'form.information': '物件情報',
    'form.investment': '投資お問い合わせ',
    'form.consultation': 'デザイン相談',
    'form.other': 'その他',
    'form.selectTimeline': 'タイムラインを選択',
    'form.immediate': '即座',
    'form.months1-3': '1-3ヶ月',
    'form.months3-6': '3-6ヶ月',
    'form.months6-12': '6-12ヶ月',
    'form.exploring': '探索中',
    'form.selectRange': '範囲を選択',
    'form.under1m': '₹5千万未満',
    'form.range1-3m': '₹5千万 - ₹1.5億',
    'form.range3-5m': '₹1.5億 - ₹2.5億',
    'form.range5-10m': '₹2.5億 - ₹5億',
    'form.range10mPlus': '₹5億以上',
    'form.confidential': '機密',
    'form.placeholder.name': '山田太郎',
    'form.placeholder.email': 'yamada@example.com',
    'form.placeholder.phone': '+91 98765 43210',
    'form.placeholder.property': '物件名または場所',
    'form.placeholder.message': '要件について詳しく教えてください...',
    'form.cancel': 'キャンセル',
    'form.submit': 'お問い合わせを送信',
    'form.submitting': '送信中...',
    'form.thankYou': 'ありがとうございます',
    'form.success': 'お問い合わせを受け付けました。コンシェルジュチームがまもなくご連絡いたします。',
    'form.error': 'フォームの送信中にエラーが発生しました。もう一度お試しください。',
    
    // AI Chat
    'chat.title': 'Urban Nestコンシェルジュ',
    'chat.available': '利用可能',
    'chat.placeholder': '建築や可用性についてお問い合わせください...',
    'chat.greeting': 'こんにちは。私はあなたのUrban Nestコンシェルジュです。今日はポートフォリオについてどのようにお手伝いできますか？',
  },
  hi: {
    // Navbar
    'nav.portfolio': 'पोर्टफोलियो',
    'nav.philosophy': 'दर्शन',
    'nav.legacy': 'विरासत',
    'nav.intelligence': 'बुद्धिमत्ता',
    'nav.concierge': 'कॉन्सीयर्ज',
    
    // Hero
    'hero.exclusively': 'विशेष रूप से Urban Nest',
    'hero.title1': 'शांत',
    'hero.title2': 'लक्जरी की कला।',
    'hero.description': 'निवासों का एक क्यूरेटेड संग्रह जहां वास्तुशिल्प आत्मा सटीक इंजीनियरिंग से मिलती है।',
    'hero.discover': 'एस्टेट खोजें',
    'hero.viewings': 'निजी दौरे',
    
    // App sections
    'app.excellence': 'उत्कृष्टता',
    'app.living': 'जीवन एक',
    'app.acquired': 'अर्जित स्वाद है।',
    'app.belief': 'Urban Nest में, हम मानते हैं कि एक घर किसी की पहचान की सबसे गहरी अभिव्यक्ति है। हम वैश्विक रियल एस्टेट के अवांट-गार्डे का प्रतिनिधित्व करते हैं।',
    'app.inquire': 'निजी तौर पर पूछताछ करें',
    'app.future': 'भविष्य',
    'app.residential': 'आवासीय है।',
    'app.request': 'प्रस्तुति अनुरोध करें',
    'app.contact': 'सलाहकार से संपर्क करें',
    
    // ScrollReveal
    'scroll.evolution': 'विकास',
    'scroll.beyond': 'दीवारों से परे।',
    'scroll.detail': 'अटूट विस्तार।',
    'scroll.engineering': 'हमारी इंजीनियरिंग टीम हर प्रोजेक्ट पर 4,000 से अधिक घंटे खर्च करती है, यह सुनिश्चित करते हुए कि हर जोड़, सामग्री और लाइट फिक्सचर इरादे की एक कृति है।',
    
    // PropertyGrid
    'property.collections': 'संग्रह',
    'property.excellence': 'क्यूरेटेड उत्कृष्टता।',
    'property.all': 'सभी सूची',
    'property.exclusive': 'विशेष',
    'property.archived': 'संग्रहीत',
    'property.explore': 'अंतरिक्ष का अन्वेषण करें',
    'property.bedrooms': 'बेडरूम',
    
    // Footer
    'footer.explore': 'अन्वेषण करें',
    'footer.residential': 'आवासीय',
    'footer.commercial': 'व्यावसायिक',
    'footer.architecture': 'वास्तुकला',
    'footer.designLab': 'डिज़ाइन लैब',
    'footer.services': 'सेवाएं',
    'footer.advisory': 'निजी सलाह',
    'footer.relocation': 'स्थानांतरण',
    'footer.staging': 'स्टेजिंग',
    'footer.financing': 'वित्तपोषण',
    'footer.company': 'कंपनी',
    'footer.story': 'हमारी कहानी',
    'footer.impact': 'प्रभाव',
    'footer.press': 'प्रेस',
    'footer.careers': 'करियर',
    'footer.offices': 'Urban Nest कार्यालय',
    'footer.copyright': '© 2024 Urban Nest Estates. सभी अधिकार सुरक्षित।',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'सेवा की शर्तें',
    'footer.cookies': 'कुकी सेटिंग्स',
    
    // Concierge Form
    'form.title': 'कॉन्सीयर्ज पूछताछ',
    'form.subtitle': 'हम 24 घंटों के भीतर जवाब देंगे',
    'form.name': 'पूरा नाम',
    'form.email': 'ईमेल पता',
    'form.phone': 'फोन नंबर',
    'form.inquiry': 'पूछताछ का प्रकार',
    'form.property': 'रुचि की संपत्ति',
    'form.timeline': 'समयसीमा',
    'form.budget': 'बजट सीमा',
    'form.message': 'अतिरिक्त संदेश',
    'form.select': 'एक विकल्प चुनें',
    'form.viewing': 'निजी दौरा',
    'form.information': 'संपत्ति की जानकारी',
    'form.investment': 'निवेश पूछताछ',
    'form.consultation': 'डिज़ाइन परामर्श',
    'form.other': 'अन्य',
    'form.selectTimeline': 'समयसीमा चुनें',
    'form.immediate': 'तत्काल',
    'form.months1-3': '1-3 महीने',
    'form.months3-6': '3-6 महीने',
    'form.months6-12': '6-12 महीने',
    'form.exploring': 'बस अन्वेषण कर रहे हैं',
    'form.selectRange': 'सीमा चुनें',
    'form.under1m': '₹5 करोड़ से कम',
    'form.range1-3m': '₹5 करोड़ - ₹15 करोड़',
    'form.range3-5m': '₹15 करोड़ - ₹25 करोड़',
    'form.range5-10m': '₹25 करोड़ - ₹50 करोड़',
    'form.range10mPlus': '₹50 करोड़+',
    'form.confidential': 'गोपनीय',
    'form.placeholder.name': 'राम शर्मा',
    'form.placeholder.email': 'ram@example.com',
    'form.placeholder.phone': '+91 98765 43210',
    'form.placeholder.property': 'संपत्ति का नाम या स्थान',
    'form.placeholder.message': 'अपनी आवश्यकताओं के बारे में और बताएं...',
    'form.cancel': 'रद्द करें',
    'form.submit': 'पूछताछ सबमिट करें',
    'form.submitting': 'सबमिट हो रहा है...',
    'form.thankYou': 'धन्यवाद',
    'form.success': 'आपकी पूछताछ प्राप्त हो गई है। हमारी कॉन्सीयर्ज टीम जल्द ही आपसे संपर्क करेगी।',
    'form.error': 'आपके फॉर्म को सबमिट करने में एक त्रुटि हुई। कृपया पुनः प्रयास करें।',
    
    // AI Chat
    'chat.title': 'Urban Nest कॉन्सीयर्ज',
    'chat.available': 'अभी उपलब्ध',
    'chat.placeholder': 'वास्तुकला या उपलब्धता के बारे में पूछताछ करें...',
    'chat.greeting': 'नमस्कार। मैं आपका Urban Nest कॉन्सीयर्ज हूं। मैं आज हमारे पोर्टफोलियो के साथ आपकी कैसे सहायता कर सकता हूं?',
  },
};

const languageNames: Record<Language, string> = {
  en: 'English',
  fr: 'Français',
  es: 'Español',
  de: 'Deutsch',
  it: 'Italiano',
  zh: '中文',
  ja: '日本語',
  hi: 'हिन्दी',
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // Get from localStorage or default to browser language
    const saved = localStorage.getItem('urban-nest-language') as Language;
    if (saved && translations[saved]) {
      return saved;
    }
    const browserLang = navigator.language.split('-')[0] as Language;
    return translations[browserLang] ? browserLang : 'en';
  });

  useEffect(() => {
    localStorage.setItem('urban-nest-language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export { languageNames };

